export default function AboutUs(){
  return (
    <div className="about-us">
      <h2>Who are we?</h2>
      <p>Welcome to BalckList, where we provide a powerful and user-friendly tool for verifying whether a company or individual is listed in the FBI, Interpol, or OFAC public databases as wanted individuals or sanctioned entities. Our website is designed to provide a simple and efficient way for individuals and businesses to stay compliant with international laws and regulations related to financial transactions, trade, and other activities.By using our platform, our users can quickly and easily check whether a company or individual is listed in any of these databases, which can help them avoid any potential legal or reputational risks.</p>
      <p>Compliance is an integral aspect of business operations that refers to the adherence to laws, regulations, and industry standards set by governing bodies. The importance of compliance cannot be overstated, as it ensures ethical and legal business practices, builds trust with stakeholders, and helps businesses avoid legal and financial risks.Industries such as finance, healthcare, and legal are particularly susceptible to the risks of non-compliance, as they operate within complex and constantly evolving regulatory environments. However, compliance is equally important for businesses of all sizes and industries, as it helps establish a positive reputation and fosters a culture of responsible and transparent business practices.</p>
      <p>Adherence to compliance regulations is not only an ethical and legal obligation, but it is also a strategic business imperative. Compliance helps protect business assets, avoid legal and financial risks, and demonstrate a commitment to operating in a responsible and transparent manner. Ultimately, compliance is a key component of a sustainable and successful business that is respected by all stakeholders.Whether you are a business owner, compliance officer, or an individual looking to stay compliant with international laws and regulations, our website provides a reliable and convenient solution for verifying whether a company or individual is listed in the FBI, Interpol, or OFAC public databases as wanted individuals or sanctioned individuals/entities. We take pride in providing our users with a seamless experience that is both fast and easy to use.</p>
      <h2>SDNs</h2>
      <p>The penalties for doing business with SDNs can be severe and can vary depending on the specific circumstances of the case. Penalties can include fines, imprisonment, asset forfeiture, and denial of export privileges.</p>
      <p>In the United States, penalties for violating sanctions and engaging in business dealings with SDNs are enforced by the Office of Foreign Assets Control (OFAC), which is an agency within the US Department of the Treasury. The OFAC has the authority to impose civil penalties, which can range from thousands to millions of dollars depending on the severity of the violation. Criminal penalties can also be imposed in cases of willful or egregious violations, which can result in imprisonment and even higher fines.</p>
      <p>In addition to financial and legal penalties, violations can also result in reputational damage, loss of business opportunities, and loss of access to financial markets. It's important for businesses and individuals to exercise caution and due diligence in their dealings and transactions to avoid engaging in business with SDNs and violating sanctions regulations.</p>
      <h2>Stay compliant - protect your business!</h2>
    </div>
    
  )
}