# Generated by Django 4.2 on 2023-04-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Searched_Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='search_app.database')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.search')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='search_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_app.search_type'),
        ),
        migrations.AddField(
            model_name='search',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Result_Match_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250)),
                ('database_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='search_app.database')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_app.match_identification')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.search')),
                ('search_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_app.search_type')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.search')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_legal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.search')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='search_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_app.search_type'),
        ),
    ]
