# Generated by Django 4.2 on 2023-04-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='search_id',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='search_id',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='result_match_history',
            old_name='database_id',
            new_name='database',
        ),
        migrations.RenameField(
            model_name='result_match_history',
            old_name='search_id',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='searched_databases',
            old_name='database_id',
            new_name='database',
        ),
        migrations.RenameField(
            model_name='searched_databases',
            old_name='search_id',
            new_name='search',
        ),
    ]
