# Generated by Django 4.2 on 2023-04-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_rename_search_id_entity_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='dob',
            field=models.DateField(blank=True, default='YYYY-MM-DD', null=True),
        ),
    ]
